---
title: "Production of LaTeX Documents"
bibliography: memoiR.bib
output: 
  rmarkdown::html_document:
    toc: yes
    toc_float: yes
vignette: >
  %\VignetteIndexEntry{LaTeX}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
set.seed(97310)
```

Producing a PDF file from a R Markdown (`.Rmd`) document requires several steps:

- **knitR** [@Xie2015] runs the code chunks to produce results and figures.
- **bookdown** [@Xie2016] [or **rmarkdown**: @Xie2018] produces a plain Markdown document.
**memoiR** templates all rely on **bookdown** to benefit from cross references and figure/table numbering.
- Pandoc[^1] is run to produce either directly an HTML document or a LaTeX file (`.tex`).
The bibliography of HTML documents is processed by Pandoc at this stage[^2].
**memoiR** templates delay it for LaTeX documents.
*- A LaTeX engine is run to compile the LaTeX file and produce a PDF document.
It uses reference management software (BibTeX[^3] or Biber[^4]) and a LaTeX package (natbib[^5] or biblatex[^6]) for bibliography. 

[^1]: https://pandoc.org/
[^2]: https://pandoc.org/MANUAL.html#citations
[^3]: http://www.bibtex.org/
[^4]: https://en.wikipedia.org/wiki/Biber_(LaTeX)
[^5]: https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Natbib
[^6]: https://en.wikibooks.org/wiki/LaTeX/Bibliographies_with_biblatex_and_biber

**memoiR** templates rely on XeLaTeX[^7] to compile LaTeX documents to PDF files.
Among XeLaTex advantages over the classical pdflatex engine[^8], including native UTF-8 encoding, language support by Polyglossia[^9] rather than Babel[^10] (required by pdflatex) is similar to that of Pandoc to produce HTML formats, based on IETF language tags[^11] such as "en-US".
In short, this solution is simpler and more robust: just fill the `lang` field in the document header.

[^7]: https://en.wikipedia.org/wiki/XeTeX
[^8]: https://en.wikipedia.org/wiki/PdfTeX
[^9]: https://ctan.org/pkg/polyglossia
[^10]: https://ctan.org/pkg/babel
[^11]: https://en.wikipedia.org/wiki/IETF_language_tag

In the _memoir_ template, bibliography is managed by biber and biblatex.
This appears to be the best solution for long documents, allowing sidenote citations and cross-references from the bibliography to the text containing the citation.
The bibliographic style is _verbose-inote_[^12] by default: it can be changed in the memoir header.

[^12]: https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/biblatex/doc/examples/73-style-verbose-inote-biber.pdf

In short documents, i.e. articles and presentations, bibtex and natbib are preferred because the advanced formatting abilities of biblatex are not very useful, more citation styles are available (`.bst` files[^13]) and many journals expect them to be used.

[^13]: https://www.reed.edu/cis/help/LaTeX/bibtexstyles.html

# References
