on:
  push:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
      - name: Install Ghostscript
        run: |
          brew install ghostscript
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr", "pkgdown", "tinytex"))
          tinytex::install_tinytex()
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Test coverage
        run: covr::codecov(type="all")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Build Gallery
        run: memoiR::knit_all()
        shell: Rscript {0}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gallery
          path: docs/
      - name: Pkgdown
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, clean = TRUE)'
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: R-CMD-check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          # Artifact name
          name: gallery
          # Destination path: tmp to preserve docs
          path: gallery
      - name: Move gallery files to docs
        run: mv -v gallery/* docs/
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          email: ${{ secrets.EMAIL }}
          build_dir: docs
          jekyll: no
