on:
  push:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
      - name: Install Ghostscript
        run: |
          brew install ghostscript
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr", "pkgdown", "tinytex"))
          tinytex::install_tinytex()
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Upload gallery artifact
        uses: actions/upload-artifact@v1
        with:
          name: gallery
          path: tests/gallery
      - name: Test coverage
        run: covr::codecov(type="all")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Pkgdown
        run: pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}
      # - name: Build Gallery
      #   run: memoiR::knit_all()
      #   shell: Rscript {0}
      - name: Upload pkgdown artifact
        uses: actions/upload-artifact@v1
        with:
          name: pkgdown
          path: docs
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: R-CMD-check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download pkgdown artifact
        uses: actions/download-artifact@v1
        with:
          name: pkgdown
          path: docs
      - name: Download gallery artifact
        uses: actions/download-artifact@v1
        with:
          name: gallery
          path: docs/gallery
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          email: ${{ secrets.EMAIL }}
          build_dir: docs
          jekyll: no
