on:
  push:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v2
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install Ghostscript
        run: |
          brew install ghostscript
      - name: Install dependencies
        run: |
          # Package check
          install.packages(c("remotes", "rcmdcheck", "covr", "pkgdown", "tinytex", "roxygen2"))
          # TinyTeX to test templates
          install.packages("tinytex")
          tinytex::install_tinytex(bundle = "TinyTeX")
          # Packages for pkgdown articles
          install.packages(c("dplyr", "kableExtra"))*
          # Packages declared in DESCRIPTION
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Roxygenize
        run: roxygen2::roxygenize()
        shell: Rscript {0}
      - uses: EndBug/add-and-commit@v9
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Test coverage
        run: covr::codecov(type = "all")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Pkgdown
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
      - name: Build Gallery
        run: memoiR::knit_all()
        shell: Rscript {0}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: R-CMD-check
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ${{ secrets.EMAIL }}
          build_dir: .
          jekyll: no
